"""empty message

Revision ID: 1b8ebf744483
Revises: 3e2e59299f8a
Create Date: 2018-04-27 13:45:36.369845

"""

# revision identifiers, used by Alembic.
revision = '1b8ebf744483'
down_revision = '3e2e59299f8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ASR_ID', sa.String(length=255), nullable=True),
    sa.Column('AREASQFT', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel')
    ### end Alembic commands ###
