"""empty message

Revision ID: 24235535d44f
Revises: 35d00db2deb9
Create Date: 2018-04-27 14:44:49.518560

"""

# revision identifiers, used by Alembic.
revision = '24235535d44f'
down_revision = '35d00db2deb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
