"""empty message

Revision ID: 35d00db2deb9
Revises: 761211e8d960
Create Date: 2018-04-27 14:44:45.180851

"""

# revision identifiers, used by Alembic.
revision = '35d00db2deb9'
down_revision = '761211e8d960'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UNIQUEID', sa.String(length=255), nullable=True),
    sa.Column('ADDRESS', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parcel', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('parcel', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcel', 'updated_at')
    op.drop_column('parcel', 'created_at')
    op.drop_table('tree')
    ### end Alembic commands ###
