"""empty message

Revision ID: 3e2e59299f8a
Revises: 911f338dc1e3
Create Date: 2018-04-18 11:47:29.536776

"""

# revision identifiers, used by Alembic.
revision = '3e2e59299f8a'
down_revision = '911f338dc1e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
