"""empty message

Revision ID: 6229948ee25b
Revises: 1b8ebf744483
Create Date: 2018-04-27 14:06:08.668567

"""

# revision identifiers, used by Alembic.
revision = '6229948ee25b'
down_revision = '1b8ebf744483'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
