"""empty message

Revision ID: 761211e8d960
Revises: 6229948ee25b
Create Date: 2018-04-27 14:06:18.944035

"""

# revision identifiers, used by Alembic.
revision = '761211e8d960'
down_revision = '6229948ee25b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
