"""empty message

Revision ID: 911f338dc1e3
Revises: ed657e16ce20
Create Date: 2018-04-18 11:34:23.818424

"""

# revision identifiers, used by Alembic.
revision = '911f338dc1e3'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
